# Generated by Django 4.0 on 2023-06-02 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.BigIntegerField()),
                ('unix_ts', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('event_name', models.CharField(max_length=255)),
            ],
        ),
    ]
